[project]
name = "arc"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "dotenv>=0.9.9",
    "markdown>=3.7",
    "pdfplumber>=0.11.6",
    "pypdf>=5.4.0",
    "python-docx>=1.1.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "sympy>=1.13.3",
]
